apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}

data:
  USER_SERVICE_URL: "{{ .Values.configMap.userServiceUrl }}"
  PRODUCT_SERVICE_URL: "{{ .Values.configMap.productServiceUrl }}"
  PAYMENT_SERVICE_URL: "{{ .Values.configMap.paymentServiceUrl }}"
  ORDER_SERVICE_URL: "{{ .Values.configMap.orderServiceUrl }}"
